### ISSUE TITLE
KB to CVE

### ISSUE THREAD

**Issue by MindaugasRam** [haginara/msrc-python#4]
Would it be possible to have KB to CVE search instead?

**Comment by haginara** [comment]
Hi @MindaugasRam 
Thank you for giving your interest on my project.

MSRC API doesn't supports to search with the KB.
But I updated the script to supports the search with KB on latest version
```
msrc.py search KB5014699
```
It only returns first matched the KB with catalog URL.
https://catalog.update.microsoft.com/Search.aspx?q=KB5014699

I hope it helps you :) 
Thank you
